server:
  servlet:
    context-path: /approve
spring:
  profiles:
    active: dev
  resources:
    static-locations:
      - classpath:/static/
      - classpath:/templates/
      - classpath:/tempFile/
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 10
      minimum-idle: 0
      connectionTimeout: 30000
      idleTimeout: 15000
      maxLifetime: 30000
      validation-timeout: 300
      leakDetectionThreshold: 10000
      connection-test-query: select 1 from dual
  jms:
    pub-sub-domain: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
#logging:
#  level:
#    - org.springframework: trace